### ISSUE TITLE
[Docs] No clear documentation for deploying Bot Framework VA template using Azure DevOps

### ISSUE THREAD

**Issue by pravinambekar** [microsoft/botframework-solutions#3779]
Hello There,
I am looking for a way to configure **Virtual Assistant template** enabled QnAMaker bot resources to be created using Azure DevOps.
My Primary understanding is that we need to use ARM deployment stage in pipeline to trigger resource creation.
![image](https://user-images.githubusercontent.com/41193836/112470236-70ab1780-8d90-11eb-9fc1-162e0b5d8834.png)

But i am not sure how we are going to execute deploy.ps1 (PowerShell script) that enables KB creation once resources gets created.

Another way i was thinking of using Azure PowerShell to execute Deploy.ps1 but that seems not working.
![image](https://user-images.githubusercontent.com/41193836/112470339-8e787c80-8d90-11eb-9279-56b8e552a900.png)

**Is there any document/sample that can direct me about how can I deploy QnAMaker based Bot in Azure using DevOps.**

In current implementation from local PowerShell we are successfully deploying all the resources and are able to create and configure QnA knowledgebase through script execution

PS: we are using Linux platform for hosting all the resources

Any help greatly appreciated :) 
 
@lauren-mills

**Comment by lauren-mills** [comment]
Hi, internally we execute the deploy.ps1 script from a PowerShell task in ADO. 

We use the following task (yaml) to run the deploy.ps1 script:
```
steps:
- powershell: |
   Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
   
   az login --service-principal --username "<your-service-principal>" --password "<your-service-principal-pw>" --tenant "<your-azure-tenant>"
   
   ./Deployment/Scripts/deploy.ps1 -name $(VirtualAssistantBotName) -location $(Location) -languages "en-us" -appId $(VirtualAssistantBotAppId) -appPassword $(VirtualAssistantBotAppPassword) -createLuisAuthoring -luisAuthoringRegion $(LuisAuthoringRegion) -logFolder "Deployment"
  errorActionPreference: continue
  pwsh: true
  workingDirectory: 'samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/'
  displayName: 'Deploy: VA'
  continueOnError: true
```

You also need to install the BF CLI tools in a prior step, just as you do locally.
